# **ТЕОРІЯ ЙМОВІРНОСТІ ТА МАТЕМАТИЧНА СТАТИСТИКА**
## *Лабораторна робота №3* - Елементи дисперсійного аналізу

### **Завдання**
##### *Розробити зошит Mathematica для проведення дисперсійного аналізу(визначення впливу фактора на ознаку). Вихідні дані змоделювати у вигляді 5-ти груп, кожна з яких відповідає за певний ступінь дії фактора(дані в кожній групі моделюються як певне фіксоване значення плюс або мінус невелике по відношенню до початкового значення випадкове число)*

In [1]:
import numpy as np
from scipy.stats import f

#### Генерування набору даних

In [2]:
gen = np.random.rand(5,6) * 30 + 20
print(gen)

[[46.22752839 21.12553932 44.57573453 31.04260946 33.94533467 40.0617166 ]
 [23.38265485 28.97474201 26.05231499 26.38086012 37.31887224 33.6876188 ]
 [38.84073309 46.09127899 47.54433352 34.56705455 33.47227246 41.1688405 ]
 [21.59800319 28.74623759 30.8456017  48.08412621 48.3580705  27.31281363]
 [48.39476407 32.88959999 41.15234925 26.15921081 20.09325028 22.6988512 ]]


*Дані з прикладу для перевірки*

In [3]:
sample = np.array([
    [25.5, 36.2, 22.8, 30.2, 32.5, 28.4],
    [28.5, 40.6, 42.8, 36.4, 22.4, 29.6],
    [24.4, 38.6, 48.4, 50.2, 28.4, 22.8],
    [29.5, 52.8, 24.2, 22.8, 56.2, 48.4]
])

In [4]:
groups = gen
grp_num = len(groups)

#### Створення списків з довжинами та середніми

In [5]:
n = np.array([len(groups[i]) for i in range(grp_num)])
m = np.mean(groups, axis=1)
print(n)
print(m)

[6 6 6 6 6]
[36.16307716 29.2995105  40.28075218 34.15747547 31.89800427]


#### Обчислення внутрішньогрупового середньоквадратичного відхилення в квадраті

In [6]:
numer = np.sum((groups - np.transpose(np.resize(m, (n[0], grp_num)))) ** 2)
denom = sum(n) - grp_num
D1 = numer / denom
print(D1)

80.2714960569513


#### Обчислення міжгрупового середньоквадратичного відхилення в квадраті

In [7]:
D2 = np.sum((m - np.mean(groups)) ** 2 * n)
print(D2)

420.10431913198295


#### Значення статистики

In [8]:
F = D2 / D1
print(F)

5.23354291084753


#### Межа критичної області

In [9]:
fdist = f(grp_num-1, sum(n)-grp_num)
alpha = 0.01
fcritical = fdist.ppf(1-alpha)
print(fcritical)

4.1774202346456395


#### Визначення наявності впливу фактору

In [10]:
print("Вплив є істотним") if F > fcritical else print("Вплив не є істотним")

Вплив є істотним
